channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - imbalanced-learn==0.12.0
  - lightgbm==3.3.5
  - matplotlib==3.8.0
  - numpy==1.26.3
  - packaging==23.1
  - pandas==2.1.4
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.2.2
  - scipy==1.11.4
name: mlflow-env
